package org.evd.game.gencode.db;

final class DbDirtyPbTableRenderer {
    String render(DbDirtyEntityMeta entity) {
        String keyType = entity.primaryKeyField.type.boxedType();
        StringBuilder sb = new StringBuilder(16384);
        sb.append("package ").append(entity.internalTablePackage).append(";\n\n");
        sb.append("import ").append(entity.beanPackage).append(".*;\n");
        sb.append("import org.evd.game.base.DirtyObject;\n");
        if (entity.usesList()) {
            sb.append("import org.evd.game.runtime.Db.collection.XArrayList;\n");
        }
        if (entity.usesMap()) {
            sb.append("import org.evd.game.runtime.Db.collection.XHashMap;\n");
        }
        if (entity.usesSet()) {
            sb.append("import org.evd.game.runtime.Db.collection.XHashSet;\n");
        }
        sb.append("import org.evd.game.runtime.Db.serialize.DBReq;\n");
        sb.append("import org.evd.game.runtime.Db.serialize.DBRsp;\n");
        sb.append("import org.evd.game.runtime.Db.serialize.DbOpType;\n");
        sb.append("import org.evd.game.runtime.Db.serialize.DbTableField;\n");
        sb.append("import org.evd.game.runtime.Db.serialize.DbValue;\n");
        sb.append("import org.evd.game.runtime.Db.serialize.MysqlReq;\n");
        sb.append("import org.evd.game.runtime.Db.serialize.MysqlRsp;\n");
        sb.append("import org.evd.game.runtime.Db.serialize.MysqlTableMeta;\n");
        sb.append("import org.evd.game.runtime.Db.table.TTable;\n");
        sb.append("import io.protostuff.LinkedBuffer;\n");
        sb.append("import io.protostuff.ProtostuffIOUtil;\n");
        sb.append("import io.protostuff.Schema;\n");
        sb.append("import io.protostuff.runtime.RuntimeSchema;\n");
        sb.append("import java.util.ArrayList;\n");
        sb.append("import java.util.LinkedHashMap;\n");
        sb.append("import java.util.List;\n");
        sb.append("import java.util.Map;\n");
        sb.append("import java.util.Objects;\n\n");

        sb.append("public final class ").append(entity.internalTableClassName)
                .append(" extends TTable<").append(keyType).append(", ").append(entity.beanClassName).append("> {\n");
        sb.append("    private static final String TABLE_NAME = \"").append(entity.tableName()).append("\";\n");
        sb.append("    private static final String KEY_COLUMN_NAME = \"k\";\n");
        sb.append("    private static final List<String> COLUMN_NAMES = List.of(\"k\", \"v\");\n");
        sb.append("    private static final String CREATE_TABLE_SQL = \"\"\"\n");
        sb.append("            CREATE TABLE IF NOT EXISTS ").append(entity.tableName()).append(" (\n");
        sb.append("                k ").append(DbDirtyRenderSupport.renderSqlType(entity.primaryKeyField.type)).append(" NOT NULL PRIMARY KEY,\n");
        sb.append("                v MEDIUMBLOB NOT NULL\n");
        sb.append("            ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_GENERAL_CI\n");
        sb.append("            \"\"\";\n");
        sb.append("\n");
        sb.append("    private static final Schema<").append(entity.beanClassName).append("> SCHEMA = RuntimeSchema.getSchema(")
                .append(entity.beanClassName).append(".class);\n\n");

        sb.append("    private ").append(entity.internalTableClassName).append("() {\n");
        sb.append("    }\n\n");
        sb.append("    @Override\n");
        sb.append("    public String getName() {\n");
        sb.append("        return TABLE_NAME;\n");
        sb.append("    }\n\n");
        sb.append("    @Override\n");
        sb.append("    protected ").append(entity.beanClassName).append(" newValue() {\n");
        sb.append("        return new ").append(entity.beanClassName).append("();\n");
        sb.append("    }\n\n");

        sb.append("    @Override\n");
        sb.append("    public DBReq createCreateTableDBReq() {\n");
        sb.append("        return createInitReq(CREATE_TABLE_SQL, new ArrayList<>());\n");
        sb.append("    }\n\n");
        sb.append("    @Override\n");
        sb.append("    public DBReq createGetDBReq(").append(keyType).append(" key) {\n");
        sb.append("        return createReq(DbOpType.GET, List.of(createKeyField(key)));\n");
        sb.append("    }\n\n");
        sb.append("    @Override\n");
        sb.append("    protected DBReq serializeSaveDBReq(").append(entity.beanClassName).append(" value) {\n");
        sb.append("        ").append(keyType).append(" key = getPrimaryKey(value);\n");
        sb.append("        return createReq(DbOpType.SAVE, List.of(toSaveField(key, value)));\n");
        sb.append("    }\n\n");
        sb.append("    @Override\n");
        sb.append("    public DBReq createRemoveDBReq(").append(keyType).append(" key) {\n");
        sb.append("        return createReq(DbOpType.REMOVE, List.of(createKeyField(key)));\n");
        sb.append("    }\n\n");
        sb.append("    @Override\n");
        sb.append("    public DBReq createBatchGetDBReq(Map<").append(keyType).append(", ").append(entity.beanClassName).append("> map) {\n");
        sb.append("        return createReq(DbOpType.BATCH_GET, toKeyFieldList(map));\n");
        sb.append("    }\n\n");
        sb.append("    @Override\n");
        sb.append("    protected DBReq serializeBatchSaveDBReq(Map<").append(keyType).append(", ").append(entity.beanClassName).append("> map) {\n");
        sb.append("        List<DbTableField> tableFieldList = new ArrayList<>(map.size());\n");
        sb.append("        for (Map.Entry<").append(keyType).append(", ").append(entity.beanClassName).append("> entry : map.entrySet()) {\n");
        sb.append("            tableFieldList.add(toSaveField(entry.getKey(), entry.getValue()));\n");
        sb.append("        }\n");
        sb.append("        return createReq(DbOpType.BATCH_SAVE, tableFieldList);\n");
        sb.append("    }\n\n");
        sb.append("    @Override\n");
        sb.append("    public DBReq createBatchRemoveDBReq(Map<").append(keyType).append(", ").append(entity.beanClassName).append("> map) {\n");
        sb.append("        return createReq(DbOpType.BATCH_REMOVE, toKeyFieldList(map));\n");
        sb.append("    }\n\n");

        sb.append("    @Override\n");
        sb.append("    public ").append(entity.beanClassName).append(" parseGetDBRsp(DBRsp rsp) {\n");
        sb.append("        MysqlRsp mysqlRsp = requireMysqlRsp(rsp);\n");
        sb.append("        List<DbTableField> tableFieldList = mysqlRsp.getTablFieldList();\n");
        sb.append("        if (tableFieldList == null || tableFieldList.isEmpty()) {\n");
        sb.append("            return null;\n");
        sb.append("        }\n");
        sb.append("        return parseRow(tableFieldList.get(0));\n");
        sb.append("    }\n\n");
        sb.append("    @Override\n");
        sb.append("    public Map<").append(keyType).append(", ").append(entity.beanClassName).append("> parseBatchGetDBRsp(DBRsp rsp) {\n");
        sb.append("        MysqlRsp mysqlRsp = requireMysqlRsp(rsp);\n");
        sb.append("        Map<").append(keyType).append(", ").append(entity.beanClassName).append("> result = new LinkedHashMap<>();\n");
        sb.append("        List<DbTableField> tableFieldList = mysqlRsp.getTablFieldList();\n");
        sb.append("        if (tableFieldList == null || tableFieldList.isEmpty()) {\n");
        sb.append("            return result;\n");
        sb.append("        }\n");
        sb.append("        for (DbTableField tableField : tableFieldList) {\n");
        sb.append("            ").append(keyType).append(" key = parseRowKey(tableField);\n");
        sb.append("            ").append(entity.beanClassName).append(" value = parseRow(tableField);\n");
        sb.append("            if (key == null) {\n");
        sb.append("                if (value != null) {\n");
        sb.append("                    result.put(getPrimaryKey(value), value);\n");
        sb.append("                }\n");
        sb.append("                continue;\n");
        sb.append("            }\n");
        sb.append("            result.put(key, value);\n");
        sb.append("        }\n");
        sb.append("        return result;\n");
        sb.append("    }\n\n");

        sb.append("    private DBReq createInitReq(String sql, List<DbTableField> tableFieldList) {\n");
        sb.append("        MysqlReq mysqlReq = new MysqlReq();\n");
        sb.append("        mysqlReq.setTableName(TABLE_NAME);\n");
        sb.append("        MysqlTableMeta tableMeta = new MysqlTableMeta();\n");
        sb.append("        tableMeta.setKeyColumnName(KEY_COLUMN_NAME);\n");
        sb.append("        tableMeta.setColumnNames(COLUMN_NAMES);\n");
        sb.append("        mysqlReq.setTableMeta(tableMeta);\n");
        sb.append("        mysqlReq.setSql(sql);\n");
        sb.append("        mysqlReq.setTablFieldList(tableFieldList);\n\n");
        sb.append("        DBReq dbReq = new DBReq();\n");
        sb.append("        dbReq.setDbOpType(DbOpType.CREATE_TABLE);\n");
        sb.append("        dbReq.setMysqlReq(mysqlReq);\n");
        sb.append("        return dbReq;\n");
        sb.append("    }\n\n");
        sb.append("    private DBReq createReq(DbOpType opType, List<DbTableField> tableFieldList) {\n");
        sb.append("        MysqlReq mysqlReq = new MysqlReq();\n");
        sb.append("        mysqlReq.setTableName(TABLE_NAME);\n");
        sb.append("        mysqlReq.setTablFieldList(tableFieldList);\n\n");
        sb.append("        DBReq dbReq = new DBReq();\n");
        sb.append("        dbReq.setDbOpType(opType);\n");
        sb.append("        dbReq.setMysqlReq(mysqlReq);\n");
        sb.append("        return dbReq;\n");
        sb.append("    }\n\n");
        sb.append("    private DbTableField createKeyField(").append(keyType).append(" key) {\n");
        sb.append("        Objects.requireNonNull(key, \"key 不能为空\");\n");
        sb.append("        return new DbTableField(List.of(new DbValue(key)));\n");
        sb.append("    }\n\n");
        sb.append("    private List<DbTableField> toKeyFieldList(Map<").append(keyType).append(", ").append(entity.beanClassName).append("> map) {\n");
        sb.append("        requireBatchMap(map);\n");
        sb.append("        List<DbTableField> tableFieldList = new ArrayList<>(map.size());\n");
        sb.append("        for (").append(keyType).append(" key : map.keySet()) {\n");
        sb.append("            tableFieldList.add(createKeyField(key));\n");
        sb.append("        }\n");
        sb.append("        return tableFieldList;\n");
        sb.append("    }\n\n");
        sb.append("    private ").append(keyType).append(" getPrimaryKey(").append(entity.beanClassName).append(" value) {\n");
        sb.append("        return value.get").append(entity.primaryKeyField.methodSuffix).append("();\n");
        sb.append("    }\n\n");
        sb.append("    private DbTableField toSaveField(").append(keyType).append(" key, ").append(entity.beanClassName).append(" value) {\n");
        sb.append("        Objects.requireNonNull(value, \"value 不能为空\");\n");
        sb.append("        List<DbValue> valueList = new ArrayList<>(2);\n");
        sb.append("        valueList.add(new DbValue(key));\n");
        sb.append("        valueList.add(new DbValue(serializeBean(value)));\n");
        sb.append("        return new DbTableField(valueList);\n");
        sb.append("    }\n\n");
        sb.append("    private ").append(keyType).append(" parseRowKey(DbTableField tableField) {\n");
        sb.append("        List<DbValue> valueList = tableField.getValueList();\n");
        sb.append("        if (valueList == null || valueList.isEmpty()) {\n");
        sb.append("            return null;\n");
        sb.append("        }\n");
        sb.append("        return ")
                .append(DbDirtyRenderSupport.renderDbValueCast(entity.primaryKeyField.type, "valueList.get(0).getV()")).append(";\n");
        sb.append("    }\n\n");
        sb.append("    private ").append(entity.beanClassName).append(" parseRow(DbTableField tableField) {\n");
        sb.append("        List<DbValue> valueList = tableField.getValueList();\n");
        sb.append("        if (valueList == null || valueList.size() < 2) {\n");
        sb.append("            return null;\n");
        sb.append("        }\n");
        sb.append("        ").append(keyType).append(" key = ")
                .append(DbDirtyRenderSupport.renderDbValueCast(entity.primaryKeyField.type, "valueList.get(0).getV()")).append(";\n");
        sb.append("        byte[] payload = (byte[]) valueList.get(1).getV();\n");
        sb.append("        ").append(entity.beanClassName).append(" value = deserializeBean(payload);\n");
        sb.append("        value.set").append(entity.primaryKeyField.methodSuffix).append("(key);\n");
        sb.append("        value.dirty = false;\n");
        sb.append("        return value;\n");
        sb.append("    }\n\n");
        sb.append("    private MysqlRsp requireMysqlRsp(DBRsp rsp) {\n");
        sb.append("        Objects.requireNonNull(rsp, \"rsp 不能为空\");\n");
        sb.append("        if (!rsp.isSuccess()) {\n");
        sb.append("            throw new IllegalArgumentException(\"db rsp fail: \" + rsp.getExceptionMessage());\n");
        sb.append("        }\n");
        sb.append("        MysqlRsp mysqlRsp = rsp.getMysqlRsp();\n");
        sb.append("        if (mysqlRsp == null) {\n");
        sb.append("            throw new IllegalArgumentException(\"db rsp mysqlRsp 不能为空\");\n");
        sb.append("        }\n");
        sb.append("        return mysqlRsp;\n");
        sb.append("    }\n\n");
        sb.append("    private void requireBatchMap(Map<").append(keyType).append(", ").append(entity.beanClassName).append("> map) {\n");
        sb.append("        if (map == null || map.isEmpty()) {\n");
        sb.append("            throw new IllegalArgumentException(\"batch map 不能为空\");\n");
        sb.append("        }\n");
        sb.append("    }\n\n");
        sb.append("\n");
        sb.append("    private byte[] serializeBean(").append(entity.beanClassName).append(" value) {\n");
        sb.append("        LinkedBuffer buffer = LinkedBuffer.allocate();\n");
        sb.append("        try {\n");
        sb.append("            return ProtostuffIOUtil.toByteArray(value, SCHEMA, buffer);\n");
        sb.append("        } finally {\n");
        sb.append("            buffer.clear();\n");
        sb.append("        }\n");
        sb.append("    }\n\n");
        sb.append("    private ").append(entity.beanClassName).append(" deserializeBean(byte[] bytes) {\n");
        sb.append("        ").append(entity.beanClassName).append(" value = new ").append(entity.beanClassName).append("();\n");
        sb.append("        if (bytes == null || bytes.length == 0) {\n");
        sb.append("            value.dirty = false;\n");
        sb.append("            return value;\n");
        sb.append("        }\n");
        sb.append("        ProtostuffIOUtil.mergeFrom(bytes, value, SCHEMA);\n");
        sb.append("        value.dirty = false;\n");
        sb.append("        return value;\n");
        sb.append("    }\n");
        sb.append("}\n");
        return sb.toString();
    }
}
