plugins {
    id 'java'
}

group = 'org.evd'
version = '1.0-SNAPSHOT'

def serviceProjectPaths = (rootProject.findProject(':Services')?.childProjects?.values() ?: [])
        .collect { it.path }
        .sort()

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation 'org.yaml:snakeyaml:2.0'

    implementation project(':core:runtime')
    implementation project(':common')
    serviceProjectPaths.each { serviceProjectPath ->
        implementation project(serviceProjectPath)
    }

}

test {
    useJUnitPlatform()
}
