plugins {
    id 'java'
}

group = 'org.evd'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation 'org.yaml:snakeyaml:2.0'

    implementation project(":core:gencode:apt-annotation")
    implementation project(':core:runtime')
    implementation project(':common')
}

test {
    useJUnitPlatform()
}
