plugins {
    id 'java'
}

group = 'org.evd'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter

    implementation libs.snakeyaml

    implementation project(":core:gencode:apt-annotation")
    implementation project(':core:runtime')
    implementation project(':common')
}

test {
    useJUnitPlatform()
}
