rootProject.name = 'EverydayNess'
include 'core'
include 'core:runtime'
findProject(':core:runtime')?.name = 'runtime'
include 'core:gencode'
findProject(':core:gencode')?.name = 'gencode'
include 'BootStrap'
include 'Services'
include 'Services:ConnService'
findProject(':Services:ConnService')?.name = 'ConnService'
include 'Services:ConnService:ConnServiceDbDef'
findProject(':Services:ConnService:ConnServiceDbDef')?.name = 'ConnServiceDbDef'
include 'common'
include 'Services:StageService'
findProject(':Services:StageService')?.name = 'StageService'
include 'Services:StageService:StageServiceDbDef'
findProject(':Services:StageService:StageServiceDbDef')?.name = 'StageServiceDbDef'
include 'Services:LocationService'
findProject(':Services:LocationService')?.name = 'LocationService'
include 'Services:LocationService:LocationServiceDbDef'
findProject(':Services:LocationService:LocationServiceDbDef')?.name = 'LocationServiceDbDef'
include 'Services:DBService'
findProject(':Services:DBService')?.name = 'DBService'
include 'Services:DBService:DBServiceDbDef'
findProject(':Services:DBService:DBServiceDbDef')?.name = 'DBServiceDbDef'
include 'core:gencode:apt-annotation'
findProject(':core:gencode:apt-annotation')?.name = 'apt-annotation'
include 'core:gencode:apt-compiler'
findProject(':core:gencode:apt-compiler')?.name = 'apt-compiler'
include 'Release'

