rootProject.name = 'EverydayNess'
include 'core'
include 'core:runtime'
findProject(':core:runtime')?.name = 'runtime'
include 'core:gencode'
findProject(':core:gencode')?.name = 'gencode'
include 'BootStrap'
include 'Services'
include 'common'
include 'core:gencode:apt-annotation'
findProject(':core:gencode:apt-annotation')?.name = 'apt-annotation'
include 'core:gencode:apt-compiler'
findProject(':core:gencode:apt-compiler')?.name = 'apt-compiler'
include 'Release'

def servicesRootDir = file('Services')
if (servicesRootDir.exists()) {
    servicesRootDir.eachDir { serviceDir ->
        if (!new File(serviceDir, 'build.gradle').exists()) {
            return
        }

        def serviceProjectPath = "Services:${serviceDir.name}"
        include serviceProjectPath
        findProject(":${serviceProjectPath}")?.name = serviceDir.name
    }
}