plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

sourceSets {
    main {
        java {
            srcDirs += 'src/main/java'
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    implementation libs.commons.lang3
    implementation libs.netty.all
    implementation libs.snakeyaml

    implementation libs.jeromq
    implementation libs.quartz
    implementation libs.agrona
    implementation libs.mysql.connector.j
    implementation libs.picocsv
    implementation libs.fastutil

    implementation project(':core:gencode:apt-annotation')
    annotationProcessor project(':core:gencode:apt-compiler')
}

tasks.withType(JavaCompile) {
    options.compilerArgs.addAll(['--add-exports=java.base/jdk.internal.vm=ALL-UNNAMED'])
//        options.compilerArgs.addAll(['-Xlint:unchecked'])
}

test {
    useJUnitPlatform()
    jvmArgs '--add-exports=java.base/jdk.internal.vm=ALL-UNNAMED'
}
