plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
            exclude '**/*IOSerializer.java'
            exclude '**/SerializerRegister.java'
            exclude '**/*ClientCmdRegistry.java'
            exclude '**/*ClientCmdRouteRegistry.java'
            exclude '**/*ServiceImpl.java'
        }
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    // 导入自定义注解
    implementation project(":core:gencode:apt-annotation")
    implementation project(':Services:StageService:StageServiceDbDef')
    // 指定注释处理器
    annotationProcessor project(':core:gencode:apt-compiler')
    implementation project(':core:runtime')
    implementation project(':common')

}

tasks.named('compileJava', JavaCompile) {
    options.generatedSourceOutputDirectory.set(file('src/gen-apt/java'))
    options.compilerArgs += [
            '-processor',
            'org.evd.game.gencode.ServiceProcessor,org.evd.game.gencode.rpc.RpcProcessor,org.evd.game.gencode.rpc.RpcImplProcessor,org.evd.game.gencode.client.ClientCmdProcessor,org.evd.game.gencode.serialize.SerializeIoProcessor,org.evd.game.gencode.serialize.SerializeProcessor'
    ]
}

test {
    useJUnitPlatform()
}
