plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

configurations {
    dbDefImplementation.extendsFrom implementation
}

sourceSets {
    /**
     * 这里是为了防止 Def 访问到生成的DB类;
     */
    dbDef {
        java {
            srcDirs = ['src/dbDef/java']
        }
    }
    main {
        java {
            srcDirs = ['src/main/java']
            srcDir(tasks.named('compileDbDefJava', JavaCompile).flatMap { it.options.generatedSourceOutputDirectory })
            exclude '**/*IOSerializer.java'
            exclude '**/SerializerRegister.java'
            exclude '**/*ClientCmdRegistry.java'
            exclude '**/*ClientCmdRouteRegistry.java'
            exclude '**/*ServiceImpl.java'
        }
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation project(":core:gencode:apt-annotation")
    dbDefImplementation project(":core:gencode:apt-annotation")
    annotationProcessor project(':core:gencode:apt-compiler')
    dbDefAnnotationProcessor project(':core:gencode:apt-compiler')
    implementation project(':core:runtime')
    dbDefImplementation project(':core:runtime')
    implementation project(':common')
    dbDefImplementation project(':common')
}

tasks.named('compileJava', JavaCompile) {
    dependsOn tasks.named('compileDbDefJava')
    options.compilerArgs += [
            '-processor',
            'org.evd.game.gencode.ServiceProcessor,org.evd.game.gencode.rpc.RpcProcessor,org.evd.game.gencode.rpc.RpcImplProcessor,org.evd.game.gencode.client.ClientCmdProcessor,org.evd.game.gencode.serialize.SerializeIoProcessor,org.evd.game.gencode.serialize.SerializeProcessor'
    ]
}

tasks.named('compileDbDefJava', JavaCompile) {
    options.incremental = false
    options.compilerArgs += ['-proc:only']
}

test {
    useJUnitPlatform()
}
