plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'io.netty:netty-all:4.1.112.Final'
    implementation project(':common')
    implementation project(':core:runtime')
    implementation project(':core:gencode:apt-annotation')
    implementation project(':Services:ConnService:ConnServiceDbDef')
    annotationProcessor project(':core:gencode:apt-compiler')
}

tasks.named('compileJava', JavaCompile) {
    options.generatedSourceOutputDirectory.set(file('src/gen-apt/java'))
    options.compilerArgs += [
            '-processor',
            'org.evd.game.gencode.ServiceProcessor,org.evd.game.gencode.rpc.RpcProcessor,org.evd.game.gencode.rpc.RpcImplProcessor,org.evd.game.gencode.client.ClientCmdProcessor,org.evd.game.gencode.serialize.SerializeIoProcessor,org.evd.game.gencode.serialize.SerializeProcessor'
    ]
}

test {
    useJUnitPlatform()
}
