package org.evd.game.gencode;


import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.TypeSpec;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.TypeElement;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;
import javax.tools.Diagnostic;
import javax.tools.StandardLocation;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Set;

public abstract class ProcessorBase extends AbstractProcessor {
    /** Element操作类 */
    protected Elements elementUtils;
    /** 类信息工具类 */
    protected Types typeUtils;
    /** 日志工具类 */
    protected Messager messager;
    /** 文件创建工具类 */
    protected Filer filer;

    public String getGenPath(String packageName, String className) {
        String rootPath = getProjectRootPackagePath(className);
        String packagePath = packageName.replaceAll("\\.", File.separator + File.separator);

        String path = rootPath + File.separator + packagePath + File.separator;
        println("targetPath: " + path);

        return path;
    }

    public String getProjectRootPackagePath(String className) {
        try {
            // 创建一个java类，但没真正写到磁盘，从javaFile中获得 SOURCE_OUTPUT 路径
            JavaFile jf = JavaFile.builder("", TypeSpec.classBuilder(className).build())
                    .addFileComment("This file is generated by program. Do not edit it manually")
                    .indent("    ")
                    .build();
            Path sourceOutputFile = Paths.get(filer.getResource(StandardLocation.SOURCE_OUTPUT, jf.packageName, className)
                    .toUri())
                    .normalize();
            Path sourceOutputDir = sourceOutputFile.getParent();
            if (sourceOutputDir == null) {
                throw new IllegalStateException("无法解析 SOURCE_OUTPUT 目录: " + sourceOutputFile);
            }

            String normalizedDir = sourceOutputDir.toString().replace('\\', '/');
            if (normalizedDir.endsWith("/src/gen/java")) {
                return sourceOutputDir.toString() + File.separator;
            }
            if (normalizedDir.endsWith("/src/gen-apt/java")) {
                String moduleRoot = normalizedDir.substring(0, normalizedDir.length() - "/src/gen-apt/java".length());
                return Paths.get(moduleRoot, "src", "gen", "java").toString() + File.separator;
            }

            int buildIndex = normalizedDir.indexOf("/build/");
            if (buildIndex < 0) {
                throw new IllegalStateException("无法从 SOURCE_OUTPUT 推导模块根目录: " + sourceOutputDir);
            }

            String moduleRoot = normalizedDir.substring(0, buildIndex);
            return Paths.get(moduleRoot, "src", "gen", "java").toString() + File.separator;
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);
        elementUtils = processingEnv.getElementUtils();
        typeUtils = processingEnv.getTypeUtils();
        messager = processingEnv.getMessager();
        filer = processingEnv.getFiler();

        init();
    }

    /**
     * 指明有哪些注解需要被扫描到，返回注解的全路径（包名+类名）
     */
    @Override
    public Set<String> getSupportedAnnotationTypes() {
        return supportAnnotation();
    }

    protected abstract Set<String> supportAnnotation() ;

    /**
     * 用来指定当前正在使用的Java版本，一般返回SourceVersion.latestSupported()表示最新的java版本即可
     */
    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latestSupported();
    }

    @Override
    public final boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (annotations == null || annotations.isEmpty()) return false;
        gen(annotations, roundEnv);
        return false;
    }

    protected void println(String str){
        messager.printMessage(Diagnostic.Kind.NOTE, str);
    }

    protected abstract void init();
    protected abstract void gen(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv);
}
