plugins {
    id 'java-library'
}

group = 'org.evd.game'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter

    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation project(":core:gencode:apt-annotation")

    // 注册注解，并对其生成META-INF的配置信息
    implementation libs.auto.service
    annotationProcessor libs.auto.service
    // 第三方自动生成代码框架（可以通过类的调用方式来自动生成代码，简洁高效）
    implementation libs.javapoet
    implementation libs.freemarker
    implementation libs.commons.lang3
}

//sourceCompatibility = JavaVersion.VERSION_1_8
//targetCompatibility = JavaVersion.VERSION_1_8

test {
    useJUnitPlatform()
}
