db:
  engine: mysql
  mysql:
    r2dbcUrl: "r2dbc:mysql://127.0.0.1:3306/game"
    username: "root"
    password: "123456"
    database: "game"
    autoCreate: true
    connectionTimeoutMs: 4000
    operationTimeoutMs: 10000
    batchOperationTimeoutMs: 300000
    poolInitialSize: 4
    poolMaxSize: 16
    poolMaxIdleTimeMs: 300000
    testQuery: "SELECT 1"

  mongo:
    enabled: false
    uri: "mongodb://127.0.0.1:27017"
    database: "game"

  storage:
    batchThreshold: 30
    batchPerCount: 500
    costMsWarn: 100
    batchCostMsWarn: 30000
    enableMemoryCache: false
    cacheFlushMs: 300000
