plugins {
    id 'java'
    alias(libs.plugins.protobuf)
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

def protoDir = providers.gradleProperty('protoDir')
        .orElse('proto')
        .get()

sourceSets {
    main {
        proto {
            srcDir rootProject.file(protoDir)
        }
        java {
            srcDir 'src/gen/java'
        }
    }
}

dependencies {
    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    implementation libs.snakeyaml
    implementation project(':core:runtime')

    implementation project(':core:gencode:apt-annotation')
    annotationProcessor project(':core:gencode:apt-compiler')
}

protobuf {
    protoc {
        def protocDependency = libs.protoc.get()
        artifact = "${protocDependency.module.group}:${protocDependency.module.name}:${protocDependency.version}"
    }
}

tasks.named('compileJava', JavaCompile) {
    dependsOn tasks.named('generateProto')
    options.compilerArgs += [
            '-processor',
            'lombok.launch.AnnotationProcessorHider$AnnotationProcessor,org.evd.game.gencode.serialize.SerializeIoProcessor,org.evd.game.gencode.serialize.SerializeProcessor,org.evd.game.gencode.config.ConfigProcessor'
    ]
}

tasks.named('processResources') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

test {
    useJUnitPlatform()
}
