buildscript {
    repositories {
        maven {
            url 'https://maven.aliyun.com/repository/public'
        }
        mavenCentral()
        mavenLocal()
    }
    dependencies {
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.9.4'
    }
}

plugins {
    id 'java'
}

apply plugin: 'com.google.protobuf'

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

sourceSets {
    main {
        proto {
            srcDirs += 'src/main/proto'
        }
        java {
            srcDirs += 'src/main/java'
            srcDirs += 'src/gen/java'
            exclude '**/*IOSerializer.java'
            exclude '**/SerializerRegister.java'
        }
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'org.yaml:snakeyaml:2.0'
    implementation project(':core:runtime')

    implementation project(':core:gencode:apt-annotation')
    annotationProcessor project(':core:gencode:apt-compiler')
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.25.3'
    }
}

tasks.named('compileJava', JavaCompile) {
    dependsOn tasks.named('generateProto')
    options.generatedSourceOutputDirectory.set(file('src/gen-apt/java'))
    options.compilerArgs += [
            '-processor',
            'org.evd.game.gencode.serialize.SerializeIoProcessor,org.evd.game.gencode.serialize.SerializeProcessor'
    ]
}

tasks.named('processResources') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

test {
    useJUnitPlatform()
}
