buildscript {
    repositories {
        maven {
            url 'https://maven.aliyun.com/repository/public'
        }
        mavenCentral()
        mavenLocal()
    }
    dependencies {
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.9.4'
    }
}

plugins {
    id 'java'
}

apply plugin: 'com.google.protobuf'

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

configurations {
    genImplementation.extendsFrom implementation // gen 代码模块可以用 main 的依赖
    genCompileOnly.extendsFrom compileOnly // genCompileOnly = compileOnly（只编译不打包）
    genAnnotationProcessor.extendsFrom annotationProcessor
}

sourceSets {
    main {
        proto {
            srcDirs += 'src/main/proto'
        }
        java {
            srcDirs += 'src/main/java'
        }
    }
    gen {
        java {
            srcDirs = ['src/gen/java']
        }
    }
}

def compileJavaTask = tasks.named('compileJava', JavaCompile)
def compileGenJavaTask = tasks.named('compileGenJava', JavaCompile)

// 将compileGenJavaTask 也算入sourceSet目录，这样其他模块使用引用common就能用gen
sourceSets.main.output.dir(
        compileGenJavaTask.flatMap { it.destinationDirectory },
        builtBy: compileGenJavaTask
)

idea {
    module {
        generatedSourceDirs += file('src/gen/java')
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'org.yaml:snakeyaml:2.0'
    implementation project(':core:runtime')

    implementation project(':core:gencode:apt-annotation')
    annotationProcessor project(':core:gencode:apt-compiler')
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.25.3'
    }
}

tasks.named('compileJava', JavaCompile) {
    dependsOn tasks.named('generateProto')
    options.compilerArgs += [
            '-processor',
            'org.evd.game.gencode.serialize.SerializeIoProcessor,org.evd.game.gencode.serialize.SerializeProcessor'
    ]
}

tasks.named('compileGenJava', JavaCompile) {
    dependsOn compileJavaTask
    classpath = files(compileJavaTask.flatMap { it.destinationDirectory }) + configurations.genCompileClasspath
}

tasks.named('processResources') {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

test {
    useJUnitPlatform()
}
