plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

def dbDefGeneratedJavaDir = layout.projectDirectory.dir('src/gen-db/java')

sourceSets {
    main {
        java {
            srcDirs = ['src/dbDef/java']
        }
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation project(':common')
    implementation project(':core:runtime')
    implementation project(':core:gencode:apt-annotation')
    annotationProcessor project(':core:gencode:apt-compiler')
}

tasks.named('compileJava', JavaCompile) {
    options.generatedSourceOutputDirectory.set(dbDefGeneratedJavaDir)
    options.compilerArgs += [
            '-processor', 'org.evd.game.gencode.db.DbDirtyEntityProcessor'
    ]
}

test {
    useJUnitPlatform()
}
