plugins {
    id 'java'
}

def dbDefGeneratedJavaDir = layout.projectDirectory.dir('src/gen-db/java')

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

configurations {
    dbDefImplementation.extendsFrom implementation
}

sourceSets {
    dbDef {
        java {
            srcDirs = ['src/dbDef/java']
        }
    }
    main {
        java {
            srcDirs = ['src/main/java']
            srcDir(tasks.named('compileDbDefJava', JavaCompile).flatMap { it.options.generatedSourceOutputDirectory })
        }
    }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation project(':core:gencode:apt-annotation')
    dbDefImplementation project(':core:gencode:apt-annotation')
    annotationProcessor project(':core:gencode:apt-compiler')
    dbDefAnnotationProcessor project(':core:gencode:apt-compiler')
    implementation project(':core:runtime')
    dbDefImplementation project(':core:runtime')
    implementation project(':common')
    dbDefImplementation project(':common')
    implementation 'com.zaxxer:HikariCP:5.1.0'
    implementation 'org.mongodb:mongo-java-driver:3.12.14'
    runtimeOnly 'com.mysql:mysql-connector-j:8.4.0'
}

tasks.named('compileJava', JavaCompile) {
    dependsOn tasks.named('compileDbDefJava')
    options.generatedSourceOutputDirectory.set(file('src/gen-apt/java'))
}

tasks.named('compileDbDefJava', JavaCompile) {
    options.compilerArgs += ['-proc:only']
    options.generatedSourceOutputDirectory.set(dbDefGeneratedJavaDir)
    outputs.dir(dbDefGeneratedJavaDir)
}

test {
    useJUnitPlatform()
}
